export const caseStudies = [
  {
    title: 'Farma Hájek',
    categoryCz: 'Zemědělská firma',
    categoryEn: 'Agricultural company',
    href: '/case-studies/farma-hajek',
    image: '/case-studies/farma-hajek/thumbnail.webp',
    servicesEn: [
      'marketing',
      'events - strongman',
      'web development',
      'social media management & content creation',
    ],
    servicesCz: [
      'marketing',
      'akce - strongman',
      'tvorba webu',
      'správa a tvorba obsahu pro sociální sítě',
    ],
  },
  {
    title: 'Four Seasons',
    categoryCz: 'Hotelový řetězec',
    categoryEn: 'Hotel chain',
    href: '/case-studies/four-seasons',
    image: '/case-studies/four-seasons/thumbnail.webp',
    servicesEn: ['content creation', 'marketing'],
    servicesCz: ['tvorba obsahu', 'marketing'],
  },
  {
    title: 'František Hrom',
    categoryCz: 'Slavná Osobnost',
    categoryEn: 'Famous Personality',
    href: '/case-studies/frantisek-hrom',
    image: '/case-studies/frantisek-hrom/thumbnail.webp',
    servicesCz: ['budování značky', 'marketing'],
    servicesEn: ['brand building', 'marketing'],
  },
  {
    title: 'Rozmluv se',
    categoryCz: 'Jazyková škola',
    categoryEn: 'Language school',
    href: '/case-studies/rozmluv-se',
    image: '/case-studies/rozmluv-se/thumbnail.webp',
    servicesCz: ['marketing - privedeni x novych studentu', 'tvorba obsahu'],
    servicesEn: ['marketing - bringing in x new students', 'content creation'],
  },
  {
    title: 'Escape Night',
    categoryCz: 'Pořádání Eventů',
    categoryEn: 'Organizing Events',
    href: '/case-studies/escape-nights',
    image: '/case-studies/rozmluv-se/thumbnail.webp',
    servicesCz: ['budování značky', 'akce'],
    servicesEn: ['brand building', 'events'],
  },
  {
    title: 'Heys Luggage',
    categoryCz: 'Influencerská Kampaň',
    categoryEn: 'Influencer Campaign',
    href: '/case-studies/heys-luggage',
    image: '/case-studies/rozmluv-se/thumbnail.webp',
    servicesCz: ['influencerská kampaň', 'marketing', 'tvorba obsahu'],
    servicesEn: ['influencer campaign', 'marketing', 'content creation'],
  },
]
