export const caseStudies = [
  {
    title: 'Farma Hájek',
    categoryEn: 'Agricultural company',
    categoryCz: 'Zemědělská firma',
    categoryDe: 'Landwirtschaftliches Unternehmen',
    href: '/case-studies/farma-hajek',
    image: '/case-studies/farma-hajek/thumbnail.webp',
    servicesEn: [
      'marketing',
      'events',
      'web development',
      'social media management & content creation',
    ],
    servicesCz: [
      'marketing',
      'akce',
      'tvorba webu',
      'správa a tvorba obsahu pro sociální sítě',
    ],
    servicesDe: [
      'Marketing',
      'Veranstaltungen',
      'Web-Entwicklung',
      'Verwaltung sozialer Medien und Erstellung von Inhalten',
    ],
    whoEn:
      'Farm Hájek is a Czech family farm specializing in year-round free-range chicken and hen rearing, fresh egg production, and the cultivation of high-quality potatoes. They take pride in upholding tradition and quality, not only in animal husbandry but also in the modern design of coops inspired by the Czech forest. Farm Hájek is not just a farm; they are passionate breeders and farmers who value quality and sustainability.',
    whoCz:
      'Farma Hájek je českou rodinnou farmou, která se specializuje na celoroční chov kuřat a slepic na volné podestýlce, výrobu čerstvých vajec a pěstování kvalitních brambor. S hrdostí dbají na tradici a kvalitu, a to nejen v chovu zvířat, ale i v moderním designu kurníků, které jsou inspirovány českým lesem. Farma Hájek není jen farmou, ale jsou to vášniví chovatelé a zemědělci, kteří si zakládají na kvalitě a udržitelnosti.',
    whoDe:
      'Farm Hájek ist ein tschechischer Familienbetrieb, der sich auf die ganzjährige Freilandhaltung von Hühnern und Hennen, die Produktion von Frischeiern und den Anbau hochwertiger Kartoffeln spezialisiert hat. Sie sind stolz darauf, Tradition und Qualität aufrechtzuerhalten, nicht nur in der Tierhaltung, sondern auch in der modernen, vom tschechischen Wald inspirierten Gestaltung der Ställe. Der Bauernhof Hájek ist nicht einfach nur ein Bauernhof, er ist ein leidenschaftlicher Züchter und Landwirt, der Wert auf Qualität und Nachhaltigkeit legt.',
    whatEn:
      'To increase brand awareness. Create a new, modern website. Optimize advertising campaigns. Manage social media. Build the brand online. Organize events.',
    whatCz:
      'Zvýšit podvědomí o značce. Nový, moderní web. Optimalizace reklamních kampaní. Správa sociálních sítí. Budování značky online. Organizace akcí.',
    whatDe:
      'Steigerung der Markenbekanntheit. Eine neue, moderne Website erstellen. Optimieren von Werbekampagnen. Soziale Medien verwalten. Die Marke online aufbauen. Veranstaltungen organisieren.',
  },
  {
    title: 'František Hrom',
    categoryEn: 'Famous Personality',
    categoryCz: 'Slavná Osobnost',
    categoryDe: 'Berühmte Persönlichkeiten',
    href: '/case-studies/frantisek-hrom',
    image: '/case-studies/frantisek-hrom/thumbnail.webp',
    servicesCz: ['budování značky', 'marketing'],
    servicesEn: ['brand building', 'marketing'],
    servicesDe: ['Markenbildung', 'Marketing'],
  },
  {
    title: 'Rozmluv se',
    categoryEn: 'Language school',
    categoryCz: 'Jazyková škola',
    categoryDe: 'Sprachschule',
    href: '/case-studies/rozmluv-se',
    image: '/case-studies/rozmluv-se/thumbnail.webp',
    servicesEn: ['marketing - bringing in x new students', 'content creation'],
    servicesCz: ['marketing - privedeni x novych studentu', 'tvorba obsahu'],
    servicesDe: [
      'Marketing - Gewinnung von x neuen Studenten',
      'Erstellung von Inhalten',
    ],
  },
  {
    title: 'Escape Night',
    categoryEn: 'Organizing Events',
    categoryCz: 'Pořádání Eventů',
    categoryDe: 'Organisieren von Veranstaltungen',
    href: '/case-studies/escape-nights',
    image: '/case-studies/rozmluv-se/thumbnail.webp',
    servicesEn: ['brand building', 'events'],
    servicesCz: ['budování značky', 'akce'],
    servicesDe: ['Markenbildung', 'Veranstaltungen'],
  },
  {
    title: 'Heys Luggage',
    categoryEn: 'Influencer Campaign',
    categoryCz: 'Influencerská Kampaň',
    categoryDe: 'Influencer-Kampagne',
    href: '/case-studies/heys-luggage',
    image: '/case-studies/rozmluv-se/thumbnail.webp',
    servicesEn: ['influencer campaign', 'marketing', 'content creation'],
    servicesCz: ['influencerská kampaň', 'marketing', 'tvorba obsahu'],
    servicesDe: ['Influencer-Kampagne', 'Marketing', 'Erstellung von Inhalten'],
  },
  {
    title: 'Four Seasons',
    categoryEn: 'Hotel chain',
    categoryCz: 'Hotelový řetězec',
    categoryDe: 'Hotelkette',
    href: '/case-studies/four-seasons',
    image: '/case-studies/four-seasons/thumbnail.webp',
    servicesEn: ['content creation', 'marketing'],
    servicesCz: ['tvorba obsahu', 'marketing'],
    servicesDe: ['Erstellung von Inhalten', 'Marketing'],
  },
]
